server:
  port: 8080
spring:
  application:
    name: Student Payment System
  datasource:
    url: jdbc:postgresql://localhost:5432/student_payment
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
application:
  security:
    jwt:

      # a day
      refresh-token:
        # 7 days